@DEV = http://localhost:8000/

@domain = {{DEV}}
@jsonContentType = application/json
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjczMDM4YWEzODU4ZmIxOTUzM2YxMTMiLCJhY2NvdW50IjoiaG9yc2VraXQxOTgyQGdtYWlsLmNvbSIsImF2YXRhciI6Imh0dHA6Ly9jbGlwYXJ0LWxpYnJhcnkuY29tL2ltYWdlcy82Y3BveTc4cmkucG5nIiwibmFtZSI6InRvbWFzMSIsImlhdCI6MTYwNDY0ODQyMn0.WsL0vhuclC4JNpbf1mzX_qW5V_DKAqRaf87-ULWel8s
@userId = 5f86b4e39877615b95f5ced1
@friendId = 5f73038aa3858fb19533f113
@roomId = 5f8420cccd899f2a59f24fe6

### public route
GET {{domain}}health-check
Content-Type: {{jsonContentType}}
Authorization: Bearer {{token}}

### Logout 
POST {{domain}}logout
Authorization: Bearer {{token}}
Content-Type: {{jsonContentType}}

### Login username:password
POST {{domain}}login
Content-Type: {{jsonContentType}}

{
  "account": "horsekit1982@gmail.com",
  "password": "a12345678",
  "regId": "abcd"
}

### register user
POST {{domain}}users
Content-Type: {{jsonContentType}}

{
  "name": "tomas11",
  "password": "a12345678",
  "account": "thomaslin0719@gmail.com"
}

### get user by id
GET {{domain}}users/{{userId}}
Content-Type: {{jsonContentType}}
Authorization: Bearer {{token}}

### get friends
GET {{domain}}friends
Content-Type: {{jsonContentType}}
Authorization: Bearer {{token}}


### invite user
POST {{domain}}friends/invite/{{friendId}}
Content-Type: {{jsonContentType}}
Authorization: Bearer {{token}}

### reject user
POST {{domain}}friends/reject/5f841ff158bacd2877847e70
Content-Type: {{jsonContentType}}
Authorization: Bearer {{token}}

### approve user
POST {{domain}}friends/approve/5f841ff158bacd2877847e70
Content-Type: {{jsonContentType}}
Authorization: Bearer {{token}}

### Get Messages
GET {{domain}}messages/{{roomId}}
Content-Type: {{jsonContentType}}
Authorization: Bearer {{token}}

### Create Message
POST {{domain}}messages/{{roomId}}
Content-Type: {{jsonContentType}}
Authorization: Bearer {{token}}

{
  "text": "test content from thomaslin0710",
  "image": "https://miro.medium.com/max/3760/1*OEnS6-DEn56szCwdOs2mrA.jpeg",
  "attachment": "https://ia801309.us.archive.org/5/items/HandbookOfNeuralComputingApplicationsPDFStormRG/Node.js%20Design%20Patterns%20-%20Casciaro,%20Mario%20%5BPDF%5D%5BStormRG%5D.pdf"
}

### get rooms

GET {{domain}}rooms?updateAt=2020-10-12 17:24:28.83
Content-Type: {{jsonContentType}}
Authorization: Bearer {{token}}


### create event

POST {{domain}}events
Content-Type: {{jsonContentType}}
Authorization: Bearer {{token}}

{
  "title": "event title11",
  "logo": "https://dyl80ryjxr1ke.cloudfront.net/external_assets/hero_examples/hair_beach_v1785392215/original.jpeg",
  "publicationPlace": "台北",
  "description": "description bbb",
  "meetingGeoJson": {
    "type": "Point",
    "coordinates": [
      121.35355353355406,
      25.046982934609268
    ]
  },
  "type": 0,
  "status": 0,
  "paymentMethod": 0,
  "budget": 100,
  "finalReviewAt" : "2020-11-06 11:23:22",
  "datingAt" : "2020-11-09 11:23:22"
}

### get events
GET {{domain}}events?updateAt=2020-11-06 11:26:34
Content-Type: {{jsonContentType}}
Authorization: Bearer {{token}}

### join event
POST {{domain}}events/5fa4fb65de118b078235af7c
Content-Type: {{jsonContentType}}
Authorization: Bearer {{token}}

### leave event
POST {{domain}}events/leave/5fa4fb65de118b078235af7c
Content-Type: {{jsonContentType}}
Authorization: Bearer {{token}}

###