@DEV = http://localhost:8000/

@domain = {{DEV}}
@jsonContentType = application/json
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjcyOWIyZWJjOWU5NThkMjcyYTZhMDUiLCJhY2NvdW50IjoiaG9yc2VraXQxOTgyQGdtYWlsLmNvbSIsImF2YXRhciI6Imh0dHA6Ly9jbGlwYXJ0LWxpYnJhcnkuY29tL2ltYWdlcy82Y3BveTc4cmkucG5nIiwibmFtZSI6InRvbWFzIiwiaWF0IjoxNjAxMzUxMTY1fQ.HAa1hXKa1-e1pSHqBcs1YFa350590zAEha3EVQEy7Ik
@userId = 5f729b2ebc9e958d272a6a04
@friendId = 5f72ae4b8651879982bfd96e

### public route
GET {{domain}}health-check
Content-Type: {{jsonContentType}}
Authorization: Bearer {{token}}

### Login username:password
POST {{domain}}login
Content-Type: {{jsonContentType}}

{
  "account": "horsekit1982@gmail.com",
  "password": "a12345678"
}

### register user

POST {{domain}}users
Content-Type: {{jsonContentType}}
Authorization: Bearer {{token}}

{
  "name": "tomas2",
  "password": "a12345678",
  "account": "thomaslin0710@gmail.com"
}

### get user by id
GET {{domain}}users/{{userId}}
Content-Type: {{jsonContentType}}
Authorization: Bearer {{token}}

### invite user
POST {{domain}}friends/invite/{{friendId}}
Content-Type: {{jsonContentType}}
Authorization: Bearer {{token}}

### reject user
POST {{domain}}friends/reject/{{friendId}}
Content-Type: {{jsonContentType}}
Authorization: Bearer {{token}}

###
